import { Roboto, Rubik_Mono_One, Sofadi_One } from "next/font/google";
import "./globals.css";

import { EmailProvider } from "@/components/context/EmailContext";
import { InstaDataProvider } from "@/components/context/InstaDataContext";

// Configure fonts
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  styles: ["normal", "italic"],
  display: "swap",
});

const rubikMonoOne = Rubik_Mono_One({
  subsets: ["latin"],
  weight: ["400"], // Rubik Mono One only supports normal weight
  display: "swap",
});

const sofadiOne = Sofadi_One({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <InstaDataProvider>

      <EmailProvider>  
        <html lang="en">
          <body
            className={`${roboto.variable} ${rubikMonoOne.variable} ${sofadiOne.variable}`}
          >
            {children}
          </body> 
        </html>
      </EmailProvider>
    </InstaDataProvider>
  );
}
