# Generated by Django 4.2.17 on 2025-01-10 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_searched', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=3)),
                ('insta_activity', models.CharField(max_length=60)),
                ('device_used', models.CharField(max_length=30)),
                ('most_used_app_after_insta', models.CharField(max_length=30)),
                ('client_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.email')),
            ],
        ),
    ]
