# Generated by Django 4.2.18 on 2025-03-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0003_alter_survey_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.EmailField(max_length=128)),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
